**IMPORTING LIBRARIES**

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import KernelPCA
from sklearn.metrics import r2_score

**FEATURE EXTRACTION - KERNEL PCA**

In [2]:
def kernel_pca(indep_X, n):
    kpca = KernelPCA(
        n_components=n,
        kernel='rbf',
        random_state=0
    )

    X_kpca = kpca.fit_transform(indep_X)

    return X_kpca

**TRAIN TEST SPLIT & SCALING**

In [3]:
def split_scalar(indep_X, dep_Y):

    X_train, X_test, y_train, y_test = train_test_split(
        indep_X,
        dep_Y,
        test_size=0.25,
        random_state=0
    )

    sc = StandardScaler()

    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)

    return X_train, X_test, y_train, y_test

**R2 SCORE FUNCTION**

In [4]:
def r2_prediction(regressor, X_test, y_test):

    y_pred = regressor.predict(X_test)

    r2 = r2_score(y_test, y_pred)

    return r2

**LINEAR REGRESSION**

In [5]:
def Linear(X_train, y_train, X_test, y_test):

    from sklearn.linear_model import LinearRegression

    regressor = LinearRegression()

    regressor.fit(X_train, y_train)

    r2 = r2_prediction(regressor, X_test, y_test)

    return r2

**SVM LINEAR**

In [6]:
def svm_linear(X_train, y_train, X_test, y_test):

    from sklearn.svm import SVR

    regressor = SVR(kernel='linear')

    regressor.fit(X_train, y_train)

    r2 = r2_prediction(regressor, X_test, y_test)

    return r2

**SVM RBF**

In [8]:
def svm_NL(X_train, y_train, X_test, y_test):

    from sklearn.svm import SVR

    regressor = SVR(kernel='rbf')

    regressor.fit(X_train, y_train)

    r2 = r2_prediction(regressor, X_test, y_test)

    return r2

**DECISION TREE**

In [9]:
def Decision(X_train, y_train, X_test, y_test):

    from sklearn.tree import DecisionTreeRegressor

    regressor = DecisionTreeRegressor(random_state=0)

    regressor.fit(X_train, y_train)

    r2 = r2_prediction(regressor, X_test, y_test)

    return r2

**RANDOM FOREST**

In [10]:
def Random(X_train, y_train, X_test, y_test):

    from sklearn.ensemble import RandomForestRegressor

    regressor = RandomForestRegressor(
        n_estimators=100,
        random_state=0
    )

    regressor.fit(X_train, y_train)

    r2 = r2_prediction(regressor, X_test, y_test)

    return r2

In [11]:
def create_result_table(acclin,
                        accsvml,
                        accsvmnl,
                        accdes,
                        accrf):

    dataframe = pd.DataFrame(
        index=['Kernel PCA'],
        columns=[
            'Linear',
            'SVM Linear',
            'SVM RBF',
            'Decision Tree',
            'Random Forest'
        ]
    )

    dataframe.loc['Kernel PCA', 'Linear'] = acclin
    dataframe.loc['Kernel PCA', 'SVM Linear'] = accsvml
    dataframe.loc['Kernel PCA', 'SVM RBF'] = accsvmnl
    dataframe.loc['Kernel PCA', 'Decision Tree'] = accdes
    dataframe.loc['Kernel PCA', 'Random Forest'] = accrf

    return dataframe

**DATASET LOADING**

In [12]:
dataset = pd.read_csv("prep.csv")

In [13]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

**DATA PREPROCESSING**

In [14]:
dataset = pd.get_dummies(
    dataset,
    drop_first=True
)

In [15]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,False,False,False,False,False,False,True,True,False,True
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,False,False,False,True,False,False,True
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,False,False,False,True,False,False,True
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,False,False,False,True,False,True,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,False,False,False,False,False,True,False,False,True
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,False,False,True,True,False,True,False,True,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,False,False,True,True,False,False,False,False,True
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,False,False,True,True,False,True,False,True,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,False,False,False,False,False,True,False,False,False

**INDEPENDENT & DEPENDENT**

In [16]:
indep_X = dataset.drop(
    'classification_yes',
    axis=1
)

dep_Y = dataset['classification_yes']

**APPLY KERNEL PCA**

In [17]:
X_kpca = kernel_pca(
    indep_X,
    n=5
)

**SPLIT DATA**

In [18]:
X_train, X_test, y_train, y_test = split_scalar(
    X_kpca,
    dep_Y
)

**MODEL TRAINING**

In [19]:
acclin = Linear(
    X_train,
    y_train,
    X_test,
    y_test
)

accsvml = svm_linear(
    X_train,
    y_train,
    X_test,
    y_test
)

accsvmnl = svm_NL(
    X_train,
    y_train,
    X_test,
    y_test
)

accdes = Decision(
    X_train,
    y_train,
    X_test,
    y_test
)

accrf = Random(
    X_train,
    y_train,
    X_test,
    y_test
)

**RESULT TABLE**

In [20]:
result = create_result_table(
    acclin,
    accsvml,
    accsvmnl,
    accdes,
    accrf
)

In [21]:
print("\nKernel PCA Model Comparison\n")

print(result)

# Optional
result.to_csv("KernelPCA_Result.csv")

Kernel PCA Model Comparison

              Linear SVM Linear   SVM RBF Decision Tree Random Forest
Kernel PCA  0.008082  -0.293036 -0.293303     -0.048974      -0.03761